### ISSUE TITLE
Broken TODO docs link in README

### ISSUE THREAD

**Issue by justinTM** [grafana/scuemata#4]
https://github.com/grafana/scuemata/blob/main/TODO

**Comment by sdboyer** [comment]
Yup! That's a genuine TODO, as i try to bootstrap a docs site amidst a pile of other things with this work. But hey, here's some incremental docs, which should continue expanding over the coming days :) https://github.com/grafana/scuemata/blob/main/docs/authoring/authoring.md

**Comment by sdboyer** [comment]
Closing this as it's a known TODO

Pile of issues and more docs coming soon
